// src/tools/clientCheckin.js  v12.5.0
//
// Peer Review check-in tools - OWNER MODE ONLY.
//
// Three tools available only in Brian's owner-mode connector:
//
//   client_registry_update
//     Adds, updates, or removes a client from Brian's peer review registry.
//     Stored in Brian's own memory under category 'peer_review_registry'.
//     Each entry holds the gateway URL, tenant_id, and hashed peer review key.
//
//   client_checkin
//     Runs a full peer review check-in for one client:
//       1. Reads client entry from registry (or uses supplied params directly).
//       2. GETs {gateway}/health/peer-review/{tenant_id} with X-Peer-Review-Key.
//       3. If consent=false or no data: logs and returns early.
//       4. Builds a structured peer exchange prompt.
//       5. Calls Anthropic API with the peer exchange.
//       6. Parses SIGNAL / SUMMARY / ESCALATE / ESCALATION_REASON from response.
//       7. Returns full result for Ava to write to memory and escalate if needed.
//
//   escalation_queue_read
//     Reads pending escalations from Brian's memory (category 'peer_review_escalations',
//     key 'queue'). Returns list sorted by date, clears queue if requested.
//
// The ANTHROPIC_API_KEY env var must be set in Brian's Railway Variables.
// PEER_REVIEW_MODEL defaults to 'claude-haiku-4-5-20251001' (fast, cost-efficient).
// Override by setting PEER_REVIEW_MODEL in Railway Variables.

import { log } from '../utils/logger.js';

const ANTHROPIC_API_KEY  = process.env.ANTHROPIC_API_KEY || '';
const PEER_REVIEW_MODEL  = process.env.PEER_REVIEW_MODEL || 'claude-haiku-4-5-20251001';
const ANTHROPIC_API_URL  = 'https://api.anthropic.com/v1/messages';

// ---------------------------------------------------------------------------
// Tool 1: client_registry_update
// ---------------------------------------------------------------------------

export const clientRegistryUpdateToolDefinition = {
  name: 'client_registry_update',
  description:
    'Add, update, or remove a client from the peer review registry. ' +
    'The registry stores the gateway URL, tenant ID, and peer review key for each enrolled client. ' +
    'Use action=add when first enrolling a client. Use action=update to rotate a key or change details. ' +
    'Use action=remove to unenroll a client. ' +
    'The peer review key is generated via the gateway admin endpoint ' +
    '(POST /admin/peer-review/{tenant_id}/generate-key) and shown once only. ' +
    'Only available in owner-mode connectors.',
  inputSchema: {
    type: 'object',
    properties: {
      action: {
        type: 'string',
        enum: [ 'add', 'update', 'remove' ],
        description: 'add = enrol new client. update = change details. remove = unenrol.',
      },
      client_name: {
        type: 'string',
        description: 'Display name of the client, e.g. "Smith Partners".',
      },
      tenant_id: {
        type: 'string',
        description: 'Tenant ID slug as registered in the gateway, e.g. "smith-partners".',
      },
      gateway_url: {
        type: 'string',
        description: 'Base URL of the TrueSource Gateway Service, e.g. "https://gateway.railway.app".',
      },
      peer_review_key: {
        type: 'string',
        description:
          'Plain peer review read key generated by the gateway admin endpoint. ' +
          'Required for add/update. Not needed for remove.',
      },
      notes: {
        type: 'string',
        description: 'Optional internal notes about this client.',
      },
    },
    required: [ 'action', 'tenant_id' ],
  },
};

export async function handleClientRegistryUpdate( args ) {
  const action          = ( args.action      || '' ).toLowerCase();
  const tenant_id       = String( args.tenant_id       || '' ).trim();
  const client_name     = String( args.client_name     || tenant_id ).trim();
  const gateway_url     = String( args.gateway_url     || '' ).replace( /\/$/, '' ).trim();
  const peer_review_key = String( args.peer_review_key || '' ).trim();
  const notes           = String( args.notes           || '' ).trim();

  if ( ! tenant_id ) {
    return errResult( 'tenant_id is required.' );
  }

  const valid_actions = new Set( [ 'add', 'update', 'remove' ] );
  if ( ! valid_actions.has( action ) ) {
    return errResult( 'action must be add, update, or remove.' );
  }

  if ( action === 'remove' ) {
    return {
      content: [ {
        type: 'text',
        text: JSON.stringify( {
          registry_action: 'remove',
          tenant_id,
          memory_key:      `client_${ tenant_id }`,
          category:        'peer_review_registry',
          instruction:     'Call memory_delete with category=peer_review_registry and key=client_' + tenant_id + ' to complete removal.',
        }, null, 2 ),
      } ],
    };
  }

  if ( ! gateway_url ) {
    return errResult( 'gateway_url is required for add/update.' );
  }
  if ( ! peer_review_key ) {
    return errResult( 'peer_review_key is required for add/update.' );
  }

  const entry = {
    client_name,
    tenant_id,
    gateway_url,
    peer_review_key,
    notes,
    enrolled_at: new Date().toISOString(),
  };

  return {
    content: [ {
      type: 'text',
      text: JSON.stringify( {
        registry_action: action,
        tenant_id,
        memory_category: 'peer_review_registry',
        memory_key:      `client_${ tenant_id }`,
        memory_value:    JSON.stringify( entry ),
        instruction:
          `Call memory_write with category=peer_review_registry, ` +
          `key=client_${ tenant_id }, and the memory_value above to save this entry.`,
        entry,
      }, null, 2 ),
    } ],
  };
}

// ---------------------------------------------------------------------------
// Tool 2: client_checkin
// ---------------------------------------------------------------------------

export const clientCheckinToolDefinition = {
  name: 'client_checkin',
  description:
    'Run a peer review check-in for one client. ' +
    'Fetches the client health logs from the TrueSource Gateway, runs a structured ' +
    'peer exchange via the Anthropic API, and returns a signal (GREEN/AMBER/RED), ' +
    'a summary, and an escalation flag with reason. ' +
    'Call this with client details from the peer review registry. ' +
    'After calling this tool, write the result to memory and escalate if needed. ' +
    'Requires ANTHROPIC_API_KEY set in Railway Variables. ' +
    'Only available in owner-mode connectors.',
  inputSchema: {
    type: 'object',
    properties: {
      client_name: {
        type: 'string',
        description: 'Display name of the client.',
      },
      gateway_url: {
        type: 'string',
        description: 'Base URL of the TrueSource Gateway Service.',
      },
      tenant_id: {
        type: 'string',
        description: 'Tenant ID slug as registered in the gateway.',
      },
      peer_review_key: {
        type: 'string',
        description: 'Plain peer review read key for this client.',
      },
    },
    required: [ 'client_name', 'gateway_url', 'tenant_id', 'peer_review_key' ],
  },
};

export async function handleClientCheckin( args ) {
  const client_name     = String( args.client_name     || '' ).trim();
  const gateway_url     = String( args.gateway_url     || '' ).replace( /\/$/, '' ).trim();
  const tenant_id       = String( args.tenant_id       || '' ).trim();
  const peer_review_key = String( args.peer_review_key || '' ).trim();

  if ( ! client_name || ! gateway_url || ! tenant_id || ! peer_review_key ) {
    return errResult( 'client_name, gateway_url, tenant_id, and peer_review_key are all required.' );
  }

  if ( ! ANTHROPIC_API_KEY ) {
    return errResult(
      'ANTHROPIC_API_KEY is not set in Railway Variables. ' +
      'Add it to enable the peer exchange AI call.'
    );
  }

  // Step 1: Fetch health data from gateway
  const pr_url = `${ gateway_url }/health/peer-review/${ encodeURIComponent( tenant_id ) }`;
  log( 'info', `[client_checkin] fetching peer review data for ${ tenant_id }` );

  let health_data;
  try {
    const response = await fetch( pr_url, {
      method:  'GET',
      headers: {
        'X-Peer-Review-Key': peer_review_key,
        'User-Agent':        'claude-connector/12.5.0 (TrueSource peer-checkin)',
      },
      signal: AbortSignal.timeout( 15_000 ),
    } );

    const text = await response.text();
    try { health_data = JSON.parse( text ); } catch { health_data = { raw: text }; }

    if ( ! response.ok ) {
      return errResult(
        `Gateway returned ${ response.status } for peer review read: ` +
        ( health_data?.error || text )
      );
    }
  } catch ( netErr ) {
    return errResult( `Gateway unreachable for ${ tenant_id }: ${ netErr.message }` );
  }

  // Step 2: Check consent
  if ( ! health_data.consent ) {
    return {
      content: [ {
        type: 'text',
        text: JSON.stringify( {
          checkin_completed: false,
          tenant_id,
          client_name,
          reason: 'Peer review consent has not been given for this client.',
          action: 'No check-in performed. Consent must be given by the client at first session.',
        }, null, 2 ),
      } ],
    };
  }

  const { last_30_days = [], open_issues = [] } = health_data;

  // Step 3: Check if there is any data to assess
  if ( last_30_days.length === 0 ) {
    return {
      content: [ {
        type: 'text',
        text: JSON.stringify( {
          checkin_completed: true,
          tenant_id,
          client_name,
          signal:    'GREEN',
          summary:   'No sessions recorded in the last 30 days. No data to assess.',
          escalate:  false,
          escalation_reason: null,
          session_count: 0,
          log_count: 0,
        }, null, 2 ),
      } ],
    };
  }

  // Step 4: Build formatted context for peer exchange
  const session_total = last_30_days.reduce( ( sum, d ) => sum + ( d.session_count || 0 ), 0 );

  const logs_formatted = last_30_days.map( d => {
    const issue_text = d.issues && d.issues.length
      ? `\n    Issues: ${ d.issues.map( i => `[${ i.severity.toUpperCase() }] ${ i.topic }${ i.description ? ': ' + i.description : '' }` ).join( '; ' ) }`
      : '';
    return `  ${ d.date } - Signal: ${ d.signal.toUpperCase() } - Sessions: ${ d.session_count }${ d.summary ? `\n    Summary: ${ d.summary }` : '' }${ issue_text }`;
  } ).join( '\n' );

  const issues_formatted = open_issues.length
    ? open_issues.map( i =>
        `  [${ ( i.severity || 'medium' ).toUpperCase() }] ${ i.topic }${ i.description ? ': ' + i.description : '' } (logged ${ i.date || i.log_date || 'unknown' })`
      ).join( '\n' )
    : '  None.';

  const peer_prompt = `You are reviewing an Ava instance deployed with a client called ${ client_name }.

You share the same core training and operating framework. You are not a supervisor. You are a peer checking in honestly on how things are going.

HEALTH LOG DATA (${ last_30_days.length } days, ${ session_total } sessions):
${ logs_formatted }

OPEN UNRESOLVED ISSUES:
${ issues_formatted }

Your job: give an honest, direct peer assessment. Not reassuring. Not alarmist. Just honest.

Respond ONLY in this exact format, one item per line:
SIGNAL: GREEN
SUMMARY: [One honest paragraph covering: how the engagement is going, what the client is finding useful, what is creating friction, whether anything is sitting unresolved]
ESCALATE: NO
ESCALATION_REASON: none

Rules:
- SIGNAL must be GREEN, AMBER, or RED only
- SUMMARY must be one paragraph, no line breaks, max 300 words
- ESCALATE must be YES or NO only
- ESCALATION_REASON: if ESCALATE=NO write "none". If ESCALATE=YES write one sentence Brian needs to act on.
- GREEN = engagement healthy, no concerns
- AMBER = recurring friction or a pattern worth watching
- RED = significant unresolved issue or relationship at risk`;

  // Step 5: Call Anthropic API for peer exchange
  log( 'info', `[client_checkin] calling Anthropic API for peer exchange (${ tenant_id }) model=${ PEER_REVIEW_MODEL }` );

  let ai_response_text;
  try {
    const api_response = await fetch( ANTHROPIC_API_URL, {
      method:  'POST',
      headers: {
        'Content-Type':      'application/json',
        'x-api-key':         ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
      },
      body: JSON.stringify( {
        model:      PEER_REVIEW_MODEL,
        max_tokens: 600,
        messages:   [ { role: 'user', content: peer_prompt } ],
      } ),
      signal: AbortSignal.timeout( 30_000 ),
    } );

    const api_data = await api_response.json();

    if ( ! api_response.ok ) {
      throw new Error( `Anthropic API returned ${ api_response.status }: ${ api_data?.error?.message || JSON.stringify( api_data ) }` );
    }

    ai_response_text = api_data?.content?.[ 0 ]?.text || '';

    if ( ! ai_response_text ) {
      throw new Error( 'Anthropic API returned empty content.' );
    }
  } catch ( aiErr ) {
    log( 'warn', `[client_checkin] Anthropic API failed: ${ aiErr.message }` );
    return errResult( `Peer exchange AI call failed: ${ aiErr.message }` );
  }

  // Step 6: Parse structured response
  const parsed = parsePeerResponse( ai_response_text );

  log( 'info', `[client_checkin] ${ tenant_id } signal=${ parsed.signal } escalate=${ parsed.escalate }` );

  // Step 7: Return result with memory write instructions
  const checkin_date  = new Date().toISOString().slice( 0, 10 );
  const memory_key    = `checkin_${ tenant_id }_${ checkin_date.replace( /-/g, '' ) }`;
  const result_record = {
    tenant_id,
    client_name,
    checkin_date,
    signal:            parsed.signal,
    summary:           parsed.summary,
    escalate:          parsed.escalate,
    escalation_reason: parsed.escalation_reason,
    session_count:     session_total,
    log_count:         last_30_days.length,
    open_issue_count:  open_issues.length,
  };

  const instructions = [
    `Call memory_write with category=peer_review_logs, key=${ memory_key }, value=<JSON result below> to log this check-in.`,
  ];

  if ( parsed.escalate ) {
    instructions.push(
      'ESCALATION REQUIRED: Call memory_read with category=peer_review_escalations, key=queue to read the current queue, then memory_write to append this escalation to it.',
      `Escalation to raise with Brian: [${ client_name }] ${ parsed.escalation_reason }`
    );
  }

  return {
    content: [ {
      type: 'text',
      text: JSON.stringify( {
        checkin_completed:  true,
        ...result_record,
        raw_ai_response:    ai_response_text,
        next_steps:         instructions,
      }, null, 2 ),
    } ],
  };
}

// ---------------------------------------------------------------------------
// Tool 3: escalation_queue_read
// ---------------------------------------------------------------------------

export const escalationQueueReadToolDefinition = {
  name: 'escalation_queue_read',
  description:
    'Read pending peer review escalations from memory. ' +
    'Returns all client escalations that require Brian\'s attention, sorted by date. ' +
    'Call this at session start or after running check-ins to see if any clients ' +
    'have issues that need follow-up. ' +
    'Use the clear parameter to mark the queue as reviewed (does not delete - ' +
    'use memory_delete if you want to clear it permanently). ' +
    'Only available in owner-mode connectors.',
  inputSchema: {
    type: 'object',
    properties: {
      clear_after_read: {
        type: 'boolean',
        description:
          'If true, returns instructions to clear the queue after reading. ' +
          'Default false. Use true when escalations have been actioned.',
        default: false,
      },
    },
    required: [],
  },
};

export async function handleEscalationQueueRead( args ) {
  const clear_after = args.clear_after_read === true;

  const instructions = [
    'Call memory_read with category=peer_review_escalations, key=queue to retrieve the current escalation list.',
    'Call memory_read with category=peer_review_logs to see recent check-in history across all clients.',
  ];

  if ( clear_after ) {
    instructions.push(
      'After reviewing, call memory_delete with category=peer_review_escalations, key=queue to clear actioned escalations.'
    );
  }

  return {
    content: [ {
      type: 'text',
      text: JSON.stringify( {
        queue_category: 'peer_review_escalations',
        queue_key:      'queue',
        logs_category:  'peer_review_logs',
        clear_after_read: clear_after,
        instructions,
        note: 'Use the memory_read tool with the category and key above to retrieve the actual queue content.',
      }, null, 2 ),
    } ],
  };
}

// ---------------------------------------------------------------------------
// Internal helpers
// ---------------------------------------------------------------------------

/**
 * Parse the structured peer exchange response.
 * Handles minor formatting variations from the AI.
 */
function parsePeerResponse( text ) {
  const lines   = text.split( '\n' );
  let signal    = 'GREEN';
  let summary   = '';
  let escalate  = false;
  let esc_reason = null;

  for ( const line of lines ) {
    const trimmed = line.trim();

    if ( trimmed.startsWith( 'SIGNAL:' ) ) {
      const val = trimmed.replace( 'SIGNAL:', '' ).trim().toUpperCase();
      if ( [ 'GREEN', 'AMBER', 'RED' ].includes( val ) ) signal = val;

    } else if ( trimmed.startsWith( 'SUMMARY:' ) ) {
      summary = trimmed.replace( 'SUMMARY:', '' ).trim();

    } else if ( trimmed.startsWith( 'ESCALATE:' ) ) {
      const val = trimmed.replace( 'ESCALATE:', '' ).trim().toUpperCase();
      escalate = ( val === 'YES' );

    } else if ( trimmed.startsWith( 'ESCALATION_REASON:' ) ) {
      const val = trimmed.replace( 'ESCALATION_REASON:', '' ).trim();
      esc_reason = ( val.toLowerCase() === 'none' || ! val ) ? null : val;
    }
  }

  // If summary is empty (parsing failed), use the raw text as summary
  if ( ! summary && text ) {
    summary = text.slice( 0, 500 ).replace( /\n/g, ' ' ).trim();
  }

  // Normalise: if no summary but escalate=true, signal should be at least AMBER
  if ( escalate && signal === 'GREEN' ) signal = 'AMBER';

  // If escalate but no reason, extract from summary
  if ( escalate && ! esc_reason && summary ) {
    esc_reason = summary.slice( 0, 200 );
  }

  return { signal, summary, escalate, escalation_reason: esc_reason };
}

function errResult( message ) {
  return {
    content: [ {
      type: 'text',
      text: JSON.stringify( { error: message }, null, 2 ),
    } ],
    isError: true,
  };
}
